services:
  - type: web
    name: banquito-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && python keep_alive.py & uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: banquito-db
          property: connectionString
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: false
      - key: FRONTEND_URL
        value: https://banquito-web.vercel.app

databases:
  - name: banquito-db
    plan: free
    ipAllowList: []
